version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: bravo1_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mediatool_v2
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: